version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/demo-app/
hooks:
  BeforeInstall:
    - location: scripts/uninstall.sh
      runas: root
  AfterInstall:
    - location: scripts/executable.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
  ValidateService:
    - location: scripts/serviceCheck.sh
      timeout: 3600
      runas: root
