version: 0.0
os: linux
files:
  - source: templates
    destination: /home/ubuntu/demo-app/
  - source: main
    destination: /home/ubuntu/demo-app/
  - source: .env
    destination: /home/ubuntu/demo-app/    
hooks:
  BeforeInstall:
    - location: scripts/uninstall.sh
      runas: root
  AfterInstall:
    - location: scripts/executable.sh
      timeout: 10
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 10
      runas: root
  ValidateService:
    - location: scripts/serviceCheck.sh
      timeout: 3600
      runas: root
