version: 0.2

phases:
  pre_build:
    commands:
      - echo Test started on `date`
  build:
    commands:
      - echo "Here could be your test! :)"
  post_build:
    commands:
      - echo Test completed on `date`